/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cooltrickshome_MyLogger */

#ifndef _Included_cooltrickshome_MyLogger
#define _Included_cooltrickshome_MyLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cooltrickshome_MyLogger
 * Method:    GetKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cooltrickshome_MyLogger_GetKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
