/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyLogger */

#ifndef _Included_MyLogger
#define _Included_MyLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyLogger
 * Method:    GetKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MyLogger_GetKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

